package koma.gui.element.emoji.category;

val Activities = listOf(
        EmojiSymbol("🎃", "1f383", "jack-o-lantern"),
        EmojiSymbol("🎄", "1f384", "Christmas tree"),
        EmojiSymbol("🎆", "1f386", "fireworks"),
        EmojiSymbol("🎇", "1f387", "sparkler"),
        EmojiSymbol("✨", "2728", "sparkles"),
        EmojiSymbol("🎈", "1f388", "balloon"),
        EmojiSymbol("🎉", "1f389", "party popper"),
        EmojiSymbol("🎊", "1f38a", "confetti ball"),
        EmojiSymbol("🎋", "1f38b", "tanabata tree"),
        EmojiSymbol("🎍", "1f38d", "pine decoration"),
        EmojiSymbol("🎎", "1f38e", "Japanese dolls"),
        EmojiSymbol("🎏", "1f38f", "carp streamer"),
        EmojiSymbol("🎐", "1f390", "wind chime"),
        EmojiSymbol("🎑", "1f391", "moon viewing ceremony"),
        EmojiSymbol("🎀", "1f380", "ribbon"),
        EmojiSymbol("🎁", "1f381", "wrapped gift"),
        EmojiSymbol("🎗", "1f397", "reminder ribbon"),
        EmojiSymbol("🎟", "1f39f", "admission tickets"),
        EmojiSymbol("🎫", "1f3ab", "ticket"),
        EmojiSymbol("🎖", "1f396", "military medal"),
        EmojiSymbol("🏆", "1f3c6", "trophy"),
        EmojiSymbol("🏅", "1f3c5", "sports medal"),
        EmojiSymbol("🥇", "1f947", "1st place medal"),
        EmojiSymbol("🥈", "1f948", "2nd place medal"),
        EmojiSymbol("🥉", "1f949", "3rd place medal"),
        EmojiSymbol("⚽", "26bd", "soccer ball"),
        EmojiSymbol("⚾", "26be", "baseball"),
        EmojiSymbol("🏀", "1f3c0", "basketball"),
        EmojiSymbol("🏐", "1f3d0", "volleyball"),
        EmojiSymbol("🏈", "1f3c8", "american football"),
        EmojiSymbol("🏉", "1f3c9", "rugby football"),
        EmojiSymbol("🎾", "1f3be", "tennis"),
        EmojiSymbol("🎱", "1f3b1", "pool 8 ball"),
        EmojiSymbol("🎳", "1f3b3", "bowling"),
        EmojiSymbol("🏏", "1f3cf", "cricket game"),
        EmojiSymbol("🏑", "1f3d1", "field hockey"),
        EmojiSymbol("🏒", "1f3d2", "ice hockey"),
        EmojiSymbol("🏓", "1f3d3", "ping pong"),
        EmojiSymbol("🏸", "1f3f8", "badminton"),
        EmojiSymbol("🥊", "1f94a", "boxing glove"),
        EmojiSymbol("🥋", "1f94b", "martial arts uniform"),
        EmojiSymbol("🥅", "1f945", "goal net"),
        EmojiSymbol("🎯", "1f3af", "direct hit"),
        EmojiSymbol("⛳", "26f3", "flag in hole"),
        EmojiSymbol("⛸", "26f8", "ice skate"),
        EmojiSymbol("🎣", "1f3a3", "fishing pole"),
        EmojiSymbol("🎽", "1f3bd", "running shirt"),
        EmojiSymbol("🎿", "1f3bf", "skis"),
        EmojiSymbol("🛷", "1f6f7", "sled"),
        EmojiSymbol("🥌", "1f94c", "curling stone"),
        EmojiSymbol("🎮", "1f3ae", "video game"),
        EmojiSymbol("🕹", "1f579", "joystick"),
        EmojiSymbol("🎲", "1f3b2", "game die"),
        EmojiSymbol("♠", "2660", "spade suit"),
        EmojiSymbol("♥", "2665", "heart suit"),
        EmojiSymbol("♦", "2666", "diamond suit"),
        EmojiSymbol("♣", "2663", "club suit"),
        EmojiSymbol("🃏", "1f0cf", "joker"),
        EmojiSymbol("🀄", "1f004", "mahjong red dragon"),
        EmojiSymbol("🎴", "1f3b4", "flower playing cards")
)
