package koma.gui.element.emoji.category;

val Flags = listOf(
        EmojiSymbol("🏁", "1f3c1", "chequered flag"),
        EmojiSymbol("🚩", "1f6a9", "triangular flag"),
        EmojiSymbol("🎌", "1f38c", "crossed flags"),
        EmojiSymbol("🏴", "1f3f4", "black flag"),
        EmojiSymbol("🏳", "1f3f3", "white flag"),
        EmojiSymbol("🏳️‍🌈", "1f3f3-fe0f-200d-1f308", "rainbow flag"),
        EmojiSymbol("🇦🇨", "1f1e6-1f1e8", "Ascension Island"),
        EmojiSymbol("🇦🇩", "1f1e6-1f1e9", "Andorra"),
        EmojiSymbol("🇦🇪", "1f1e6-1f1ea", "United Arab Emirates"),
        EmojiSymbol("🇦🇫", "1f1e6-1f1eb", "Afghanistan"),
        EmojiSymbol("🇦🇬", "1f1e6-1f1ec", "Antigua & Barbuda"),
        EmojiSymbol("🇦🇮", "1f1e6-1f1ee", "Anguilla"),
        EmojiSymbol("🇦🇱", "1f1e6-1f1f1", "Albania"),
        EmojiSymbol("🇦🇲", "1f1e6-1f1f2", "Armenia"),
        EmojiSymbol("🇦🇴", "1f1e6-1f1f4", "Angola"),
        EmojiSymbol("🇦🇶", "1f1e6-1f1f6", "Antarctica"),
        EmojiSymbol("🇦🇷", "1f1e6-1f1f7", "Argentina"),
        EmojiSymbol("🇦🇸", "1f1e6-1f1f8", "American Samoa"),
        EmojiSymbol("🇦🇹", "1f1e6-1f1f9", "Austria"),
        EmojiSymbol("🇦🇺", "1f1e6-1f1fa", "Australia"),
        EmojiSymbol("🇦🇼", "1f1e6-1f1fc", "Aruba"),
        EmojiSymbol("🇦🇽", "1f1e6-1f1fd", "Åland Islands"),
        EmojiSymbol("🇦🇿", "1f1e6-1f1ff", "Azerbaijan"),
        EmojiSymbol("🇧🇦", "1f1e7-1f1e6", "Bosnia & Herzegovina"),
        EmojiSymbol("🇧🇧", "1f1e7-1f1e7", "Barbados"),
        EmojiSymbol("🇧🇩", "1f1e7-1f1e9", "Bangladesh"),
        EmojiSymbol("🇧🇪", "1f1e7-1f1ea", "Belgium"),
        EmojiSymbol("🇧🇫", "1f1e7-1f1eb", "Burkina Faso"),
        EmojiSymbol("🇧🇬", "1f1e7-1f1ec", "Bulgaria"),
        EmojiSymbol("🇧🇭", "1f1e7-1f1ed", "Bahrain"),
        EmojiSymbol("🇧🇮", "1f1e7-1f1ee", "Burundi"),
        EmojiSymbol("🇧🇯", "1f1e7-1f1ef", "Benin"),
        EmojiSymbol("🇧🇱", "1f1e7-1f1f1", "St. Barthélemy"),
        EmojiSymbol("🇧🇲", "1f1e7-1f1f2", "Bermuda"),
        EmojiSymbol("🇧🇳", "1f1e7-1f1f3", "Brunei"),
        EmojiSymbol("🇧🇴", "1f1e7-1f1f4", "Bolivia"),
        EmojiSymbol("🇧🇶", "1f1e7-1f1f6", "Caribbean Netherlands"),
        EmojiSymbol("🇧🇷", "1f1e7-1f1f7", "Brazil"),
        EmojiSymbol("🇧🇸", "1f1e7-1f1f8", "Bahamas"),
        EmojiSymbol("🇧🇹", "1f1e7-1f1f9", "Bhutan"),
        EmojiSymbol("🇧🇻", "1f1e7-1f1fb", "Bouvet Island"),
        EmojiSymbol("🇧🇼", "1f1e7-1f1fc", "Botswana"),
        EmojiSymbol("🇧🇾", "1f1e7-1f1fe", "Belarus"),
        EmojiSymbol("🇧🇿", "1f1e7-1f1ff", "Belize"),
        EmojiSymbol("🇨🇦", "1f1e8-1f1e6", "Canada"),
        EmojiSymbol("🇨🇨", "1f1e8-1f1e8", "Cocos (Keeling) Islands"),
        EmojiSymbol("🇨🇩", "1f1e8-1f1e9", "Congo - Kinshasa"),
        EmojiSymbol("🇨🇫", "1f1e8-1f1eb", "Central African Republic"),
        EmojiSymbol("🇨🇬", "1f1e8-1f1ec", "Congo - Brazzaville"),
        EmojiSymbol("🇨🇭", "1f1e8-1f1ed", "Switzerland"),
        EmojiSymbol("🇨🇮", "1f1e8-1f1ee", "Côte d’Ivoire"),
        EmojiSymbol("🇨🇰", "1f1e8-1f1f0", "Cook Islands"),
        EmojiSymbol("🇨🇱", "1f1e8-1f1f1", "Chile"),
        EmojiSymbol("🇨🇲", "1f1e8-1f1f2", "Cameroon"),
        EmojiSymbol("🇨🇳", "1f1e8-1f1f3", "China"),
        EmojiSymbol("🇨🇴", "1f1e8-1f1f4", "Colombia"),
        EmojiSymbol("🇨🇵", "1f1e8-1f1f5", "Clipperton Island"),
        EmojiSymbol("🇨🇷", "1f1e8-1f1f7", "Costa Rica"),
        EmojiSymbol("🇨🇺", "1f1e8-1f1fa", "Cuba"),
        EmojiSymbol("🇨🇻", "1f1e8-1f1fb", "Cape Verde"),
        EmojiSymbol("🇨🇼", "1f1e8-1f1fc", "Curaçao"),
        EmojiSymbol("🇨🇽", "1f1e8-1f1fd", "Christmas Island"),
        EmojiSymbol("🇨🇾", "1f1e8-1f1fe", "Cyprus"),
        EmojiSymbol("🇨🇿", "1f1e8-1f1ff", "Czechia"),
        EmojiSymbol("🇩🇪", "1f1e9-1f1ea", "Germany"),
        EmojiSymbol("🇩🇬", "1f1e9-1f1ec", "Diego Garcia"),
        EmojiSymbol("🇩🇯", "1f1e9-1f1ef", "Djibouti"),
        EmojiSymbol("🇩🇰", "1f1e9-1f1f0", "Denmark"),
        EmojiSymbol("🇩🇲", "1f1e9-1f1f2", "Dominica"),
        EmojiSymbol("🇩🇴", "1f1e9-1f1f4", "Dominican Republic"),
        EmojiSymbol("🇩🇿", "1f1e9-1f1ff", "Algeria"),
        EmojiSymbol("🇪🇦", "1f1ea-1f1e6", "Ceuta & Melilla"),
        EmojiSymbol("🇪🇨", "1f1ea-1f1e8", "Ecuador"),
        EmojiSymbol("🇪🇪", "1f1ea-1f1ea", "Estonia"),
        EmojiSymbol("🇪🇬", "1f1ea-1f1ec", "Egypt"),
        EmojiSymbol("🇪🇭", "1f1ea-1f1ed", "Western Sahara"),
        EmojiSymbol("🇪🇷", "1f1ea-1f1f7", "Eritrea"),
        EmojiSymbol("🇪🇸", "1f1ea-1f1f8", "Spain"),
        EmojiSymbol("🇪🇹", "1f1ea-1f1f9", "Ethiopia"),
        EmojiSymbol("🇪🇺", "1f1ea-1f1fa", "European Union"),
        EmojiSymbol("🇫🇮", "1f1eb-1f1ee", "Finland"),
        EmojiSymbol("🇫🇯", "1f1eb-1f1ef", "Fiji"),
        EmojiSymbol("🇫🇰", "1f1eb-1f1f0", "Falkland Islands"),
        EmojiSymbol("🇫🇲", "1f1eb-1f1f2", "Micronesia"),
        EmojiSymbol("🇫🇴", "1f1eb-1f1f4", "Faroe Islands"),
        EmojiSymbol("🇫🇷", "1f1eb-1f1f7", "France"),
        EmojiSymbol("🇬🇦", "1f1ec-1f1e6", "Gabon"),
        EmojiSymbol("🇬🇧", "1f1ec-1f1e7", "United Kingdom"),
        EmojiSymbol("🇬🇩", "1f1ec-1f1e9", "Grenada"),
        EmojiSymbol("🇬🇪", "1f1ec-1f1ea", "Georgia"),
        EmojiSymbol("🇬🇫", "1f1ec-1f1eb", "French Guiana"),
        EmojiSymbol("🇬🇬", "1f1ec-1f1ec", "Guernsey"),
        EmojiSymbol("🇬🇭", "1f1ec-1f1ed", "Ghana"),
        EmojiSymbol("🇬🇮", "1f1ec-1f1ee", "Gibraltar"),
        EmojiSymbol("🇬🇱", "1f1ec-1f1f1", "Greenland"),
        EmojiSymbol("🇬🇲", "1f1ec-1f1f2", "Gambia"),
        EmojiSymbol("🇬🇳", "1f1ec-1f1f3", "Guinea"),
        EmojiSymbol("🇬🇵", "1f1ec-1f1f5", "Guadeloupe"),
        EmojiSymbol("🇬🇶", "1f1ec-1f1f6", "Equatorial Guinea"),
        EmojiSymbol("🇬🇷", "1f1ec-1f1f7", "Greece"),
        EmojiSymbol("🇬🇸", "1f1ec-1f1f8", "South Georgia & South Sandwich Islands"),
        EmojiSymbol("🇬🇹", "1f1ec-1f1f9", "Guatemala"),
        EmojiSymbol("🇬🇺", "1f1ec-1f1fa", "Guam"),
        EmojiSymbol("🇬🇼", "1f1ec-1f1fc", "Guinea-Bissau"),
        EmojiSymbol("🇬🇾", "1f1ec-1f1fe", "Guyana"),
        EmojiSymbol("🇭🇰", "1f1ed-1f1f0", "Hong Kong SAR China"),
        EmojiSymbol("🇭🇲", "1f1ed-1f1f2", "Heard & McDonald Islands"),
        EmojiSymbol("🇭🇳", "1f1ed-1f1f3", "Honduras"),
        EmojiSymbol("🇭🇷", "1f1ed-1f1f7", "Croatia"),
        EmojiSymbol("🇭🇹", "1f1ed-1f1f9", "Haiti"),
        EmojiSymbol("🇭🇺", "1f1ed-1f1fa", "Hungary"),
        EmojiSymbol("🇮🇨", "1f1ee-1f1e8", "Canary Islands"),
        EmojiSymbol("🇮🇩", "1f1ee-1f1e9", "Indonesia"),
        EmojiSymbol("🇮🇪", "1f1ee-1f1ea", "Ireland"),
        EmojiSymbol("🇮🇱", "1f1ee-1f1f1", "Israel"),
        EmojiSymbol("🇮🇲", "1f1ee-1f1f2", "Isle of Man"),
        EmojiSymbol("🇮🇳", "1f1ee-1f1f3", "India"),
        EmojiSymbol("🇮🇴", "1f1ee-1f1f4", "British Indian Ocean Territory"),
        EmojiSymbol("🇮🇶", "1f1ee-1f1f6", "Iraq"),
        EmojiSymbol("🇮🇷", "1f1ee-1f1f7", "Iran"),
        EmojiSymbol("🇮🇸", "1f1ee-1f1f8", "Iceland"),
        EmojiSymbol("🇮🇹", "1f1ee-1f1f9", "Italy"),
        EmojiSymbol("🇯🇪", "1f1ef-1f1ea", "Jersey"),
        EmojiSymbol("🇯🇲", "1f1ef-1f1f2", "Jamaica"),
        EmojiSymbol("🇯🇴", "1f1ef-1f1f4", "Jordan"),
        EmojiSymbol("🇯🇵", "1f1ef-1f1f5", "Japan"),
        EmojiSymbol("🇰🇪", "1f1f0-1f1ea", "Kenya"),
        EmojiSymbol("🇰🇬", "1f1f0-1f1ec", "Kyrgyzstan"),
        EmojiSymbol("🇰🇭", "1f1f0-1f1ed", "Cambodia"),
        EmojiSymbol("🇰🇮", "1f1f0-1f1ee", "Kiribati"),
        EmojiSymbol("🇰🇲", "1f1f0-1f1f2", "Comoros"),
        EmojiSymbol("🇰🇳", "1f1f0-1f1f3", "St. Kitts & Nevis"),
        EmojiSymbol("🇰🇵", "1f1f0-1f1f5", "North Korea"),
        EmojiSymbol("🇰🇷", "1f1f0-1f1f7", "South Korea"),
        EmojiSymbol("🇰🇼", "1f1f0-1f1fc", "Kuwait"),
        EmojiSymbol("🇰🇾", "1f1f0-1f1fe", "Cayman Islands"),
        EmojiSymbol("🇰🇿", "1f1f0-1f1ff", "Kazakhstan"),
        EmojiSymbol("🇱🇦", "1f1f1-1f1e6", "Laos"),
        EmojiSymbol("🇱🇧", "1f1f1-1f1e7", "Lebanon"),
        EmojiSymbol("🇱🇨", "1f1f1-1f1e8", "St. Lucia"),
        EmojiSymbol("🇱🇮", "1f1f1-1f1ee", "Liechtenstein"),
        EmojiSymbol("🇱🇰", "1f1f1-1f1f0", "Sri Lanka"),
        EmojiSymbol("🇱🇷", "1f1f1-1f1f7", "Liberia"),
        EmojiSymbol("🇱🇸", "1f1f1-1f1f8", "Lesotho"),
        EmojiSymbol("🇱🇹", "1f1f1-1f1f9", "Lithuania"),
        EmojiSymbol("🇱🇺", "1f1f1-1f1fa", "Luxembourg"),
        EmojiSymbol("🇱🇻", "1f1f1-1f1fb", "Latvia"),
        EmojiSymbol("🇱🇾", "1f1f1-1f1fe", "Libya"),
        EmojiSymbol("🇲🇦", "1f1f2-1f1e6", "Morocco"),
        EmojiSymbol("🇲🇨", "1f1f2-1f1e8", "Monaco"),
        EmojiSymbol("🇲🇩", "1f1f2-1f1e9", "Moldova"),
        EmojiSymbol("🇲🇪", "1f1f2-1f1ea", "Montenegro"),
        EmojiSymbol("🇲🇫", "1f1f2-1f1eb", "St. Martin"),
        EmojiSymbol("🇲🇬", "1f1f2-1f1ec", "Madagascar"),
        EmojiSymbol("🇲🇭", "1f1f2-1f1ed", "Marshall Islands"),
        EmojiSymbol("🇲🇰", "1f1f2-1f1f0", "Macedonia"),
        EmojiSymbol("🇲🇱", "1f1f2-1f1f1", "Mali"),
        EmojiSymbol("🇲🇲", "1f1f2-1f1f2", "Myanmar (Burma)"),
        EmojiSymbol("🇲🇳", "1f1f2-1f1f3", "Mongolia"),
        EmojiSymbol("🇲🇴", "1f1f2-1f1f4", "Macau SAR China"),
        EmojiSymbol("🇲🇵", "1f1f2-1f1f5", "Northern Mariana Islands"),
        EmojiSymbol("🇲🇶", "1f1f2-1f1f6", "Martinique"),
        EmojiSymbol("🇲🇷", "1f1f2-1f1f7", "Mauritania"),
        EmojiSymbol("🇲🇸", "1f1f2-1f1f8", "Montserrat"),
        EmojiSymbol("🇲🇹", "1f1f2-1f1f9", "Malta"),
        EmojiSymbol("🇲🇺", "1f1f2-1f1fa", "Mauritius"),
        EmojiSymbol("🇲🇻", "1f1f2-1f1fb", "Maldives"),
        EmojiSymbol("🇲🇼", "1f1f2-1f1fc", "Malawi"),
        EmojiSymbol("🇲🇽", "1f1f2-1f1fd", "Mexico"),
        EmojiSymbol("🇲🇾", "1f1f2-1f1fe", "Malaysia"),
        EmojiSymbol("🇲🇿", "1f1f2-1f1ff", "Mozambique"),
        EmojiSymbol("🇳🇦", "1f1f3-1f1e6", "Namibia"),
        EmojiSymbol("🇳🇨", "1f1f3-1f1e8", "New Caledonia"),
        EmojiSymbol("🇳🇪", "1f1f3-1f1ea", "Niger"),
        EmojiSymbol("🇳🇫", "1f1f3-1f1eb", "Norfolk Island"),
        EmojiSymbol("🇳🇬", "1f1f3-1f1ec", "Nigeria"),
        EmojiSymbol("🇳🇮", "1f1f3-1f1ee", "Nicaragua"),
        EmojiSymbol("🇳🇱", "1f1f3-1f1f1", "Netherlands"),
        EmojiSymbol("🇳🇴", "1f1f3-1f1f4", "Norway"),
        EmojiSymbol("🇳🇵", "1f1f3-1f1f5", "Nepal"),
        EmojiSymbol("🇳🇷", "1f1f3-1f1f7", "Nauru"),
        EmojiSymbol("🇳🇺", "1f1f3-1f1fa", "Niue"),
        EmojiSymbol("🇳🇿", "1f1f3-1f1ff", "New Zealand"),
        EmojiSymbol("🇴🇲", "1f1f4-1f1f2", "Oman"),
        EmojiSymbol("🇵🇦", "1f1f5-1f1e6", "Panama"),
        EmojiSymbol("🇵🇪", "1f1f5-1f1ea", "Peru"),
        EmojiSymbol("🇵🇫", "1f1f5-1f1eb", "French Polynesia"),
        EmojiSymbol("🇵🇬", "1f1f5-1f1ec", "Papua New Guinea"),
        EmojiSymbol("🇵🇭", "1f1f5-1f1ed", "Philippines"),
        EmojiSymbol("🇵🇰", "1f1f5-1f1f0", "Pakistan"),
        EmojiSymbol("🇵🇱", "1f1f5-1f1f1", "Poland"),
        EmojiSymbol("🇵🇲", "1f1f5-1f1f2", "St. Pierre & Miquelon"),
        EmojiSymbol("🇵🇳", "1f1f5-1f1f3", "Pitcairn Islands"),
        EmojiSymbol("🇵🇷", "1f1f5-1f1f7", "Puerto Rico"),
        EmojiSymbol("🇵🇸", "1f1f5-1f1f8", "Palestinian Territories"),
        EmojiSymbol("🇵🇹", "1f1f5-1f1f9", "Portugal"),
        EmojiSymbol("🇵🇼", "1f1f5-1f1fc", "Palau"),
        EmojiSymbol("🇵🇾", "1f1f5-1f1fe", "Paraguay"),
        EmojiSymbol("🇶🇦", "1f1f6-1f1e6", "Qatar"),
        EmojiSymbol("🇷🇪", "1f1f7-1f1ea", "Réunion"),
        EmojiSymbol("🇷🇴", "1f1f7-1f1f4", "Romania"),
        EmojiSymbol("🇷🇸", "1f1f7-1f1f8", "Serbia"),
        EmojiSymbol("🇷🇺", "1f1f7-1f1fa", "Russia"),
        EmojiSymbol("🇷🇼", "1f1f7-1f1fc", "Rwanda"),
        EmojiSymbol("🇸🇦", "1f1f8-1f1e6", "Saudi Arabia"),
        EmojiSymbol("🇸🇧", "1f1f8-1f1e7", "Solomon Islands"),
        EmojiSymbol("🇸🇨", "1f1f8-1f1e8", "Seychelles"),
        EmojiSymbol("🇸🇩", "1f1f8-1f1e9", "Sudan"),
        EmojiSymbol("🇸🇪", "1f1f8-1f1ea", "Sweden"),
        EmojiSymbol("🇸🇬", "1f1f8-1f1ec", "Singapore"),
        EmojiSymbol("🇸🇭", "1f1f8-1f1ed", "St. Helena"),
        EmojiSymbol("🇸🇮", "1f1f8-1f1ee", "Slovenia"),
        EmojiSymbol("🇸🇯", "1f1f8-1f1ef", "Svalbard & Jan Mayen"),
        EmojiSymbol("🇸🇰", "1f1f8-1f1f0", "Slovakia"),
        EmojiSymbol("🇸🇱", "1f1f8-1f1f1", "Sierra Leone"),
        EmojiSymbol("🇸🇲", "1f1f8-1f1f2", "San Marino"),
        EmojiSymbol("🇸🇳", "1f1f8-1f1f3", "Senegal"),
        EmojiSymbol("🇸🇴", "1f1f8-1f1f4", "Somalia"),
        EmojiSymbol("🇸🇷", "1f1f8-1f1f7", "Suriname"),
        EmojiSymbol("🇸🇸", "1f1f8-1f1f8", "South Sudan"),
        EmojiSymbol("🇸🇹", "1f1f8-1f1f9", "São Tomé & Príncipe"),
        EmojiSymbol("🇸🇻", "1f1f8-1f1fb", "El Salvador"),
        EmojiSymbol("🇸🇽", "1f1f8-1f1fd", "Sint Maarten"),
        EmojiSymbol("🇸🇾", "1f1f8-1f1fe", "Syria"),
        EmojiSymbol("🇸🇿", "1f1f8-1f1ff", "Swaziland"),
        EmojiSymbol("🇹🇦", "1f1f9-1f1e6", "Tristan da Cunha"),
        EmojiSymbol("🇹🇨", "1f1f9-1f1e8", "Turks & Caicos Islands"),
        EmojiSymbol("🇹🇩", "1f1f9-1f1e9", "Chad"),
        EmojiSymbol("🇹🇫", "1f1f9-1f1eb", "French Southern Territories"),
        EmojiSymbol("🇹🇬", "1f1f9-1f1ec", "Togo"),
        EmojiSymbol("🇹🇭", "1f1f9-1f1ed", "Thailand"),
        EmojiSymbol("🇹🇯", "1f1f9-1f1ef", "Tajikistan"),
        EmojiSymbol("🇹🇰", "1f1f9-1f1f0", "Tokelau"),
        EmojiSymbol("🇹🇱", "1f1f9-1f1f1", "Timor-Leste"),
        EmojiSymbol("🇹🇲", "1f1f9-1f1f2", "Turkmenistan"),
        EmojiSymbol("🇹🇳", "1f1f9-1f1f3", "Tunisia"),
        EmojiSymbol("🇹🇴", "1f1f9-1f1f4", "Tonga"),
        EmojiSymbol("🇹🇷", "1f1f9-1f1f7", "Turkey"),
        EmojiSymbol("🇹🇹", "1f1f9-1f1f9", "Trinidad & Tobago"),
        EmojiSymbol("🇹🇻", "1f1f9-1f1fb", "Tuvalu"),
        EmojiSymbol("🇹🇼", "1f1f9-1f1fc", "Taiwan"),
        EmojiSymbol("🇹🇿", "1f1f9-1f1ff", "Tanzania"),
        EmojiSymbol("🇺🇦", "1f1fa-1f1e6", "Ukraine"),
        EmojiSymbol("🇺🇬", "1f1fa-1f1ec", "Uganda"),
        EmojiSymbol("🇺🇲", "1f1fa-1f1f2", "U.S. Outlying Islands"),
        EmojiSymbol("🇺🇳", "1f1fa-1f1f3", "United Nations"),
        EmojiSymbol("🇺🇸", "1f1fa-1f1f8", "United States"),
        EmojiSymbol("🇺🇾", "1f1fa-1f1fe", "Uruguay"),
        EmojiSymbol("🇺🇿", "1f1fa-1f1ff", "Uzbekistan"),
        EmojiSymbol("🇻🇦", "1f1fb-1f1e6", "Vatican City"),
        EmojiSymbol("🇻🇨", "1f1fb-1f1e8", "St. Vincent & Grenadines"),
        EmojiSymbol("🇻🇪", "1f1fb-1f1ea", "Venezuela"),
        EmojiSymbol("🇻🇬", "1f1fb-1f1ec", "British Virgin Islands"),
        EmojiSymbol("🇻🇮", "1f1fb-1f1ee", "U.S. Virgin Islands"),
        EmojiSymbol("🇻🇳", "1f1fb-1f1f3", "Vietnam"),
        EmojiSymbol("🇻🇺", "1f1fb-1f1fa", "Vanuatu"),
        EmojiSymbol("🇼🇫", "1f1fc-1f1eb", "Wallis & Futuna"),
        EmojiSymbol("🇼🇸", "1f1fc-1f1f8", "Samoa"),
        EmojiSymbol("🇽🇰", "1f1fd-1f1f0", "Kosovo"),
        EmojiSymbol("🇾🇪", "1f1fe-1f1ea", "Yemen"),
        EmojiSymbol("🇾🇹", "1f1fe-1f1f9", "Mayotte"),
        EmojiSymbol("🇿🇦", "1f1ff-1f1e6", "South Africa"),
        EmojiSymbol("🇿🇲", "1f1ff-1f1f2", "Zambia"),
        EmojiSymbol("🇿🇼", "1f1ff-1f1fc", "Zimbabwe"),
        EmojiSymbol("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "1f3f4-e0067-e0062-e0065-e006e-e0067-e007f", "England"),
        EmojiSymbol("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "1f3f4-e0067-e0062-e0073-e0063-e0074-e007f", "Scotland"),
        EmojiSymbol("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "1f3f4-e0067-e0062-e0077-e006c-e0073-e007f", "Wales")
)
