package koma.gui.element.emoji.category;

val Food = listOf(
        EmojiSymbol("🍇", "1f347", "grapes"),
        EmojiSymbol("🍈", "1f348", "melon"),
        EmojiSymbol("🍉", "1f349", "watermelon"),
        EmojiSymbol("🍊", "1f34a", "tangerine"),
        EmojiSymbol("🍋", "1f34b", "lemon"),
        EmojiSymbol("🍌", "1f34c", "banana"),
        EmojiSymbol("🍍", "1f34d", "pineapple"),
        EmojiSymbol("🍎", "1f34e", "red apple"),
        EmojiSymbol("🍏", "1f34f", "green apple"),
        EmojiSymbol("🍐", "1f350", "pear"),
        EmojiSymbol("🍑", "1f351", "peach"),
        EmojiSymbol("🍒", "1f352", "cherries"),
        EmojiSymbol("🍓", "1f353", "strawberry"),
        EmojiSymbol("🥝", "1f95d", "kiwi fruit"),
        EmojiSymbol("🍅", "1f345", "tomato"),
        EmojiSymbol("🥥", "1f965", "coconut"),
        EmojiSymbol("🥑", "1f951", "avocado"),
        EmojiSymbol("🍆", "1f346", "eggplant"),
        EmojiSymbol("🥔", "1f954", "potato"),
        EmojiSymbol("🥕", "1f955", "carrot"),
        EmojiSymbol("🌽", "1f33d", "ear of corn"),
        EmojiSymbol("🌶", "1f336", "hot pepper"),
        EmojiSymbol("🥒", "1f952", "cucumber"),
        EmojiSymbol("🥦", "1f966", "broccoli"),
        EmojiSymbol("🍄", "1f344", "mushroom"),
        EmojiSymbol("🥜", "1f95c", "peanuts"),
        EmojiSymbol("🌰", "1f330", "chestnut"),
        EmojiSymbol("🍞", "1f35e", "bread"),
        EmojiSymbol("🥐", "1f950", "croissant"),
        EmojiSymbol("🥖", "1f956", "baguette bread"),
        EmojiSymbol("🥨", "1f968", "pretzel"),
        EmojiSymbol("🥞", "1f95e", "pancakes"),
        EmojiSymbol("🧀", "1f9c0", "cheese wedge"),
        EmojiSymbol("🍖", "1f356", "meat on bone"),
        EmojiSymbol("🍗", "1f357", "poultry leg"),
        EmojiSymbol("🥩", "1f969", "cut of meat"),
        EmojiSymbol("🥓", "1f953", "bacon"),
        EmojiSymbol("🍔", "1f354", "hamburger"),
        EmojiSymbol("🍟", "1f35f", "french fries"),
        EmojiSymbol("🍕", "1f355", "pizza"),
        EmojiSymbol("🌭", "1f32d", "hot dog"),
        EmojiSymbol("🥪", "1f96a", "sandwich"),
        EmojiSymbol("🌮", "1f32e", "taco"),
        EmojiSymbol("🌯", "1f32f", "burrito"),
        EmojiSymbol("🥙", "1f959", "stuffed flatbread"),
        EmojiSymbol("🥚", "1f95a", "egg"),
        EmojiSymbol("🍳", "1f373", "cooking"),
        EmojiSymbol("🥘", "1f958", "shallow pan of food"),
        EmojiSymbol("🍲", "1f372", "pot of food"),
        EmojiSymbol("🥣", "1f963", "bowl with spoon"),
        EmojiSymbol("🥗", "1f957", "green salad"),
        EmojiSymbol("🍿", "1f37f", "popcorn"),
        EmojiSymbol("🥫", "1f96b", "canned food"),
        EmojiSymbol("🍱", "1f371", "bento box"),
        EmojiSymbol("🍘", "1f358", "rice cracker"),
        EmojiSymbol("🍙", "1f359", "rice ball"),
        EmojiSymbol("🍚", "1f35a", "cooked rice"),
        EmojiSymbol("🍛", "1f35b", "curry rice"),
        EmojiSymbol("🍜", "1f35c", "steaming bowl"),
        EmojiSymbol("🍝", "1f35d", "spaghetti"),
        EmojiSymbol("🍠", "1f360", "roasted sweet potato"),
        EmojiSymbol("🍢", "1f362", "oden"),
        EmojiSymbol("🍣", "1f363", "sushi"),
        EmojiSymbol("🍤", "1f364", "fried shrimp"),
        EmojiSymbol("🍥", "1f365", "fish cake with swirl"),
        EmojiSymbol("🍡", "1f361", "dango"),
        EmojiSymbol("🥟", "1f95f", "dumpling"),
        EmojiSymbol("🥠", "1f960", "fortune cookie"),
        EmojiSymbol("🥡", "1f961", "takeout box"),
        EmojiSymbol("🍦", "1f366", "soft ice cream"),
        EmojiSymbol("🍧", "1f367", "shaved ice"),
        EmojiSymbol("🍨", "1f368", "ice cream"),
        EmojiSymbol("🍩", "1f369", "doughnut"),
        EmojiSymbol("🍪", "1f36a", "cookie"),
        EmojiSymbol("🎂", "1f382", "birthday cake"),
        EmojiSymbol("🍰", "1f370", "shortcake"),
        EmojiSymbol("🥧", "1f967", "pie"),
        EmojiSymbol("🍫", "1f36b", "chocolate bar"),
        EmojiSymbol("🍬", "1f36c", "candy"),
        EmojiSymbol("🍭", "1f36d", "lollipop"),
        EmojiSymbol("🍮", "1f36e", "custard"),
        EmojiSymbol("🍯", "1f36f", "honey pot"),
        EmojiSymbol("🍼", "1f37c", "baby bottle"),
        EmojiSymbol("🥛", "1f95b", "glass of milk"),
        EmojiSymbol("☕", "2615", "hot beverage"),
        EmojiSymbol("🍵", "1f375", "teacup without handle"),
        EmojiSymbol("🍶", "1f376", "sake"),
        EmojiSymbol("🍾", "1f37e", "bottle with popping cork"),
        EmojiSymbol("🍷", "1f377", "wine glass"),
        EmojiSymbol("🍸", "1f378", "cocktail glass"),
        EmojiSymbol("🍹", "1f379", "tropical drink"),
        EmojiSymbol("🍺", "1f37a", "beer mug"),
        EmojiSymbol("🍻", "1f37b", "clinking beer mugs"),
        EmojiSymbol("🥂", "1f942", "clinking glasses"),
        EmojiSymbol("🥃", "1f943", "tumbler glass"),
        EmojiSymbol("🥤", "1f964", "cup with straw"),
        EmojiSymbol("🥢", "1f962", "chopsticks"),
        EmojiSymbol("🍽", "1f37d", "fork and knife with plate"),
        EmojiSymbol("🍴", "1f374", "fork and knife"),
        EmojiSymbol("🥄", "1f944", "spoon"),
        EmojiSymbol("🔪", "1f52a", "kitchen knife"),
        EmojiSymbol("🏺", "1f3fa", "amphora")
)
