package koma.gui.element.emoji.category;

val Nature = listOf(
        EmojiSymbol("🐵", "1f435", "monkey face"),
        EmojiSymbol("🐒", "1f412", "monkey"),
        EmojiSymbol("🦍", "1f98d", "gorilla"),
        EmojiSymbol("🐶", "1f436", "dog face"),
        EmojiSymbol("🐕", "1f415", "dog"),
        EmojiSymbol("🐩", "1f429", "poodle"),
        EmojiSymbol("🐺", "1f43a", "wolf face"),
        EmojiSymbol("🦊", "1f98a", "fox face"),
        EmojiSymbol("🐱", "1f431", "cat face"),
        EmojiSymbol("🐈", "1f408", "cat"),
        EmojiSymbol("🦁", "1f981", "lion face"),
        EmojiSymbol("🐯", "1f42f", "tiger face"),
        EmojiSymbol("🐅", "1f405", "tiger"),
        EmojiSymbol("🐆", "1f406", "leopard"),
        EmojiSymbol("🐴", "1f434", "horse face"),
        EmojiSymbol("🐎", "1f40e", "horse"),
        EmojiSymbol("🦄", "1f984", "unicorn face"),
        EmojiSymbol("🦓", "1f993", "zebra"),
        EmojiSymbol("🦌", "1f98c", "deer"),
        EmojiSymbol("🐮", "1f42e", "cow face"),
        EmojiSymbol("🐂", "1f402", "ox"),
        EmojiSymbol("🐃", "1f403", "water buffalo"),
        EmojiSymbol("🐄", "1f404", "cow"),
        EmojiSymbol("🐷", "1f437", "pig face"),
        EmojiSymbol("🐖", "1f416", "pig"),
        EmojiSymbol("🐗", "1f417", "boar"),
        EmojiSymbol("🐽", "1f43d", "pig nose"),
        EmojiSymbol("🐏", "1f40f", "ram"),
        EmojiSymbol("🐑", "1f411", "ewe"),
        EmojiSymbol("🐐", "1f410", "goat"),
        EmojiSymbol("🐪", "1f42a", "camel"),
        EmojiSymbol("🐫", "1f42b", "two-hump camel"),
        EmojiSymbol("🦒", "1f992", "giraffe"),
        EmojiSymbol("🐘", "1f418", "elephant"),
        EmojiSymbol("🦏", "1f98f", "rhinoceros"),
        EmojiSymbol("🐭", "1f42d", "mouse face"),
        EmojiSymbol("🐁", "1f401", "mouse"),
        EmojiSymbol("🐀", "1f400", "rat"),
        EmojiSymbol("🐹", "1f439", "hamster face"),
        EmojiSymbol("🐰", "1f430", "rabbit face"),
        EmojiSymbol("🐇", "1f407", "rabbit"),
        EmojiSymbol("🐿", "1f43f", "chipmunk"),
        EmojiSymbol("🦔", "1f994", "hedgehog"),
        EmojiSymbol("🦇", "1f987", "bat"),
        EmojiSymbol("🐻", "1f43b", "bear face"),
        EmojiSymbol("🐨", "1f428", "koala"),
        EmojiSymbol("🐼", "1f43c", "panda face"),
        EmojiSymbol("🐾", "1f43e", "paw prints"),
        EmojiSymbol("🦃", "1f983", "turkey"),
        EmojiSymbol("🐔", "1f414", "chicken"),
        EmojiSymbol("🐓", "1f413", "rooster"),
        EmojiSymbol("🐣", "1f423", "hatching chick"),
        EmojiSymbol("🐤", "1f424", "baby chick"),
        EmojiSymbol("🐥", "1f425", "front-facing baby chick"),
        EmojiSymbol("🐦", "1f426", "bird"),
        EmojiSymbol("🐧", "1f427", "penguin"),
        EmojiSymbol("🕊", "1f54a", "dove"),
        EmojiSymbol("🦅", "1f985", "eagle"),
        EmojiSymbol("🦆", "1f986", "duck"),
        EmojiSymbol("🦉", "1f989", "owl"),
        EmojiSymbol("🐸", "1f438", "frog face"),
        EmojiSymbol("🐊", "1f40a", "crocodile"),
        EmojiSymbol("🐢", "1f422", "turtle"),
        EmojiSymbol("🦎", "1f98e", "lizard"),
        EmojiSymbol("🐍", "1f40d", "snake"),
        EmojiSymbol("🐲", "1f432", "dragon face"),
        EmojiSymbol("🐉", "1f409", "dragon"),
        EmojiSymbol("🦕", "1f995", "sauropod"),
        EmojiSymbol("🦖", "1f996", "T-Rex"),
        EmojiSymbol("🐳", "1f433", "spouting whale"),
        EmojiSymbol("🐋", "1f40b", "whale"),
        EmojiSymbol("🐬", "1f42c", "dolphin"),
        EmojiSymbol("🐟", "1f41f", "fish"),
        EmojiSymbol("🐠", "1f420", "tropical fish"),
        EmojiSymbol("🐡", "1f421", "blowfish"),
        EmojiSymbol("🦈", "1f988", "shark"),
        EmojiSymbol("🐙", "1f419", "octopus"),
        EmojiSymbol("🐚", "1f41a", "spiral shell"),
        EmojiSymbol("🦀", "1f980", "crab"),
        EmojiSymbol("🦐", "1f990", "shrimp"),
        EmojiSymbol("🦑", "1f991", "squid"),
        EmojiSymbol("🐌", "1f40c", "snail"),
        EmojiSymbol("🦋", "1f98b", "butterfly"),
        EmojiSymbol("🐛", "1f41b", "bug"),
        EmojiSymbol("🐜", "1f41c", "ant"),
        EmojiSymbol("🐝", "1f41d", "honeybee"),
        EmojiSymbol("🐞", "1f41e", "lady beetle"),
        EmojiSymbol("🦗", "1f997", "cricket"),
        EmojiSymbol("🕷", "1f577", "spider"),
        EmojiSymbol("🕸", "1f578", "spider web"),
        EmojiSymbol("🦂", "1f982", "scorpion"),
        EmojiSymbol("💐", "1f490", "bouquet"),
        EmojiSymbol("🌸", "1f338", "cherry blossom"),
        EmojiSymbol("💮", "1f4ae", "white flower"),
        EmojiSymbol("🏵", "1f3f5", "rosette"),
        EmojiSymbol("🌹", "1f339", "rose"),
        EmojiSymbol("🥀", "1f940", "wilted flower"),
        EmojiSymbol("🌺", "1f33a", "hibiscus"),
        EmojiSymbol("🌻", "1f33b", "sunflower"),
        EmojiSymbol("🌼", "1f33c", "blossom"),
        EmojiSymbol("🌷", "1f337", "tulip"),
        EmojiSymbol("🌱", "1f331", "seedling"),
        EmojiSymbol("🌲", "1f332", "evergreen tree"),
        EmojiSymbol("🌳", "1f333", "deciduous tree"),
        EmojiSymbol("🌴", "1f334", "palm tree"),
        EmojiSymbol("🌵", "1f335", "cactus"),
        EmojiSymbol("🌾", "1f33e", "sheaf of rice"),
        EmojiSymbol("🌿", "1f33f", "herb"),
        EmojiSymbol("☘", "2618", "shamrock"),
        EmojiSymbol("🍀", "1f340", "four leaf clover"),
        EmojiSymbol("🍁", "1f341", "maple leaf"),
        EmojiSymbol("🍂", "1f342", "fallen leaf"),
        EmojiSymbol("🍃", "1f343", "leaf fluttering in wind")
)
