package koma.gui.element.emoji.category;

val Objects = listOf(
        EmojiSymbol("🔇", "1f507", "muted speaker"),
        EmojiSymbol("🔈", "1f508", "speaker low volume"),
        EmojiSymbol("🔉", "1f509", "speaker medium volume"),
        EmojiSymbol("🔊", "1f50a", "speaker high volume"),
        EmojiSymbol("📢", "1f4e2", "loudspeaker"),
        EmojiSymbol("📣", "1f4e3", "megaphone"),
        EmojiSymbol("📯", "1f4ef", "postal horn"),
        EmojiSymbol("🔔", "1f514", "bell"),
        EmojiSymbol("🔕", "1f515", "bell with slash"),
        EmojiSymbol("🎼", "1f3bc", "musical score"),
        EmojiSymbol("🎵", "1f3b5", "musical note"),
        EmojiSymbol("🎶", "1f3b6", "musical notes"),
        EmojiSymbol("🎙", "1f399", "studio microphone"),
        EmojiSymbol("🎚", "1f39a", "level slider"),
        EmojiSymbol("🎛", "1f39b", "control knobs"),
        EmojiSymbol("🎤", "1f3a4", "microphone"),
        EmojiSymbol("🎧", "1f3a7", "headphone"),
        EmojiSymbol("📻", "1f4fb", "radio"),
        EmojiSymbol("🎷", "1f3b7", "saxophone"),
        EmojiSymbol("🎸", "1f3b8", "guitar"),
        EmojiSymbol("🎹", "1f3b9", "musical keyboard"),
        EmojiSymbol("🎺", "1f3ba", "trumpet"),
        EmojiSymbol("🎻", "1f3bb", "violin"),
        EmojiSymbol("🥁", "1f941", "drum"),
        EmojiSymbol("📱", "1f4f1", "mobile phone"),
        EmojiSymbol("📲", "1f4f2", "mobile phone with arrow"),
        EmojiSymbol("☎", "260e", "telephone"),
        EmojiSymbol("📞", "1f4de", "telephone receiver"),
        EmojiSymbol("📟", "1f4df", "pager"),
        EmojiSymbol("📠", "1f4e0", "fax machine"),
        EmojiSymbol("🔋", "1f50b", "battery"),
        EmojiSymbol("🔌", "1f50c", "electric plug"),
        EmojiSymbol("💻", "1f4bb", "laptop computer"),
        EmojiSymbol("🖥", "1f5a5", "desktop computer"),
        EmojiSymbol("🖨", "1f5a8", "printer"),
        EmojiSymbol("⌨", "2328", "keyboard"),
        EmojiSymbol("🖱", "1f5b1", "computer mouse"),
        EmojiSymbol("🖲", "1f5b2", "trackball"),
        EmojiSymbol("💽", "1f4bd", "computer disk"),
        EmojiSymbol("💾", "1f4be", "floppy disk"),
        EmojiSymbol("💿", "1f4bf", "optical disk"),
        EmojiSymbol("📀", "1f4c0", "dvd"),
        EmojiSymbol("🎥", "1f3a5", "movie camera"),
        EmojiSymbol("🎞", "1f39e", "film frames"),
        EmojiSymbol("📽", "1f4fd", "film projector"),
        EmojiSymbol("🎬", "1f3ac", "clapper board"),
        EmojiSymbol("📺", "1f4fa", "television"),
        EmojiSymbol("📷", "1f4f7", "camera"),
        EmojiSymbol("📸", "1f4f8", "camera with flash"),
        EmojiSymbol("📹", "1f4f9", "video camera"),
        EmojiSymbol("📼", "1f4fc", "videocassette"),
        EmojiSymbol("🔍", "1f50d", "magnifying glass tilted left"),
        EmojiSymbol("🔎", "1f50e", "magnifying glass tilted right"),
        EmojiSymbol("🔬", "1f52c", "microscope"),
        EmojiSymbol("🔭", "1f52d", "telescope"),
        EmojiSymbol("📡", "1f4e1", "satellite antenna"),
        EmojiSymbol("🕯", "1f56f", "candle"),
        EmojiSymbol("💡", "1f4a1", "light bulb"),
        EmojiSymbol("🔦", "1f526", "flashlight"),
        EmojiSymbol("🏮", "1f3ee", "red paper lantern"),
        EmojiSymbol("📔", "1f4d4", "notebook with decorative cover"),
        EmojiSymbol("📕", "1f4d5", "closed book"),
        EmojiSymbol("📖", "1f4d6", "open book"),
        EmojiSymbol("📗", "1f4d7", "green book"),
        EmojiSymbol("📘", "1f4d8", "blue book"),
        EmojiSymbol("📙", "1f4d9", "orange book"),
        EmojiSymbol("📚", "1f4da", "books"),
        EmojiSymbol("📓", "1f4d3", "notebook"),
        EmojiSymbol("📒", "1f4d2", "ledger"),
        EmojiSymbol("📃", "1f4c3", "page with curl"),
        EmojiSymbol("📜", "1f4dc", "scroll"),
        EmojiSymbol("📄", "1f4c4", "page facing up"),
        EmojiSymbol("📰", "1f4f0", "newspaper"),
        EmojiSymbol("🗞", "1f5de", "rolled-up newspaper"),
        EmojiSymbol("📑", "1f4d1", "bookmark tabs"),
        EmojiSymbol("🔖", "1f516", "bookmark"),
        EmojiSymbol("🏷", "1f3f7", "label"),
        EmojiSymbol("💰", "1f4b0", "money bag"),
        EmojiSymbol("💴", "1f4b4", "yen banknote"),
        EmojiSymbol("💵", "1f4b5", "dollar banknote"),
        EmojiSymbol("💶", "1f4b6", "euro banknote"),
        EmojiSymbol("💷", "1f4b7", "pound banknote"),
        EmojiSymbol("💸", "1f4b8", "money with wings"),
        EmojiSymbol("💳", "1f4b3", "credit card"),
        EmojiSymbol("💹", "1f4b9", "chart increasing with yen"),
        EmojiSymbol("💱", "1f4b1", "currency exchange"),
        EmojiSymbol("💲", "1f4b2", "heavy dollar sign"),
        EmojiSymbol("✉", "2709", "envelope"),
        EmojiSymbol("📧", "1f4e7", "e-mail"),
        EmojiSymbol("📨", "1f4e8", "incoming envelope"),
        EmojiSymbol("📩", "1f4e9", "envelope with arrow"),
        EmojiSymbol("📤", "1f4e4", "outbox tray"),
        EmojiSymbol("📥", "1f4e5", "inbox tray"),
        EmojiSymbol("📦", "1f4e6", "package"),
        EmojiSymbol("📫", "1f4eb", "closed mailbox with raised flag"),
        EmojiSymbol("📪", "1f4ea", "closed mailbox with lowered flag"),
        EmojiSymbol("📬", "1f4ec", "open mailbox with raised flag"),
        EmojiSymbol("📭", "1f4ed", "open mailbox with lowered flag"),
        EmojiSymbol("📮", "1f4ee", "postbox"),
        EmojiSymbol("🗳", "1f5f3", "ballot box with ballot"),
        EmojiSymbol("✏", "270f", "pencil"),
        EmojiSymbol("✒", "2712", "black nib"),
        EmojiSymbol("🖋", "1f58b", "fountain pen"),
        EmojiSymbol("🖊", "1f58a", "pen"),
        EmojiSymbol("🖌", "1f58c", "paintbrush"),
        EmojiSymbol("🖍", "1f58d", "crayon"),
        EmojiSymbol("📝", "1f4dd", "memo"),
        EmojiSymbol("💼", "1f4bc", "briefcase"),
        EmojiSymbol("📁", "1f4c1", "file folder"),
        EmojiSymbol("📂", "1f4c2", "open file folder"),
        EmojiSymbol("🗂", "1f5c2", "card index dividers"),
        EmojiSymbol("📅", "1f4c5", "calendar"),
        EmojiSymbol("📆", "1f4c6", "tear-off calendar"),
        EmojiSymbol("🗒", "1f5d2", "spiral notepad"),
        EmojiSymbol("🗓", "1f5d3", "spiral calendar"),
        EmojiSymbol("📇", "1f4c7", "card index"),
        EmojiSymbol("📈", "1f4c8", "chart increasing"),
        EmojiSymbol("📉", "1f4c9", "chart decreasing"),
        EmojiSymbol("📊", "1f4ca", "bar chart"),
        EmojiSymbol("📋", "1f4cb", "clipboard"),
        EmojiSymbol("📌", "1f4cc", "pushpin"),
        EmojiSymbol("📍", "1f4cd", "round pushpin"),
        EmojiSymbol("📎", "1f4ce", "paperclip"),
        EmojiSymbol("🖇", "1f587", "linked paperclips"),
        EmojiSymbol("📏", "1f4cf", "straight ruler"),
        EmojiSymbol("📐", "1f4d0", "triangular ruler"),
        EmojiSymbol("✂", "2702", "scissors"),
        EmojiSymbol("🗃", "1f5c3", "card file box"),
        EmojiSymbol("🗄", "1f5c4", "file cabinet"),
        EmojiSymbol("🗑", "1f5d1", "wastebasket"),
        EmojiSymbol("🔒", "1f512", "locked"),
        EmojiSymbol("🔓", "1f513", "unlocked"),
        EmojiSymbol("🔏", "1f50f", "locked with pen"),
        EmojiSymbol("🔐", "1f510", "locked with key"),
        EmojiSymbol("🔑", "1f511", "key"),
        EmojiSymbol("🗝", "1f5dd", "old key"),
        EmojiSymbol("🔨", "1f528", "hammer"),
        EmojiSymbol("⛏", "26cf", "pick"),
        EmojiSymbol("⚒", "2692", "hammer and pick"),
        EmojiSymbol("🛠", "1f6e0", "hammer and wrench"),
        EmojiSymbol("🗡", "1f5e1", "dagger"),
        EmojiSymbol("⚔", "2694", "crossed swords"),
        EmojiSymbol("🔫", "1f52b", "pistol"),
        EmojiSymbol("🏹", "1f3f9", "bow and arrow"),
        EmojiSymbol("🛡", "1f6e1", "shield"),
        EmojiSymbol("🔧", "1f527", "wrench"),
        EmojiSymbol("🔩", "1f529", "nut and bolt"),
        EmojiSymbol("⚙", "2699", "gear"),
        EmojiSymbol("🗜", "1f5dc", "clamp"),
        EmojiSymbol("⚗", "2697", "alembic"),
        EmojiSymbol("⚖", "2696", "balance scale"),
        EmojiSymbol("🔗", "1f517", "link"),
        EmojiSymbol("⛓", "26d3", "chains"),
        EmojiSymbol("💉", "1f489", "syringe"),
        EmojiSymbol("💊", "1f48a", "pill"),
        EmojiSymbol("🚬", "1f6ac", "cigarette"),
        EmojiSymbol("⚰", "26b0", "coffin"),
        EmojiSymbol("⚱", "26b1", "funeral urn"),
        EmojiSymbol("🗿", "1f5ff", "moai"),
        EmojiSymbol("🛢", "1f6e2", "oil drum"),
        EmojiSymbol("🔮", "1f52e", "crystal ball"),
        EmojiSymbol("🛒", "1f6d2", "shopping cart")
)
