package koma.gui.element.emoji.category;

val Symbols = listOf(
        EmojiSymbol("🏧", "1f3e7", "ATM sign"),
        EmojiSymbol("🚮", "1f6ae", "litter in bin sign"),
        EmojiSymbol("🚰", "1f6b0", "potable water"),
        EmojiSymbol("♿", "267f", "wheelchair symbol"),
        EmojiSymbol("🚹", "1f6b9", "men’s room"),
        EmojiSymbol("🚺", "1f6ba", "women’s room"),
        EmojiSymbol("🚻", "1f6bb", "restroom"),
        EmojiSymbol("🚼", "1f6bc", "baby symbol"),
        EmojiSymbol("🚾", "1f6be", "water closet"),
        EmojiSymbol("🛂", "1f6c2", "passport control"),
        EmojiSymbol("🛃", "1f6c3", "customs"),
        EmojiSymbol("🛄", "1f6c4", "baggage claim"),
        EmojiSymbol("🛅", "1f6c5", "left luggage"),
        EmojiSymbol("⚠", "26a0", "warning"),
        EmojiSymbol("🚸", "1f6b8", "children crossing"),
        EmojiSymbol("⛔", "26d4", "no entry"),
        EmojiSymbol("🚫", "1f6ab", "prohibited"),
        EmojiSymbol("🚳", "1f6b3", "no bicycles"),
        EmojiSymbol("🚭", "1f6ad", "no smoking"),
        EmojiSymbol("🚯", "1f6af", "no littering"),
        EmojiSymbol("🚱", "1f6b1", "non-potable water"),
        EmojiSymbol("🚷", "1f6b7", "no pedestrians"),
        EmojiSymbol("📵", "1f4f5", "no mobile phones"),
        EmojiSymbol("🔞", "1f51e", "no one under eighteen"),
        EmojiSymbol("☢", "2622", "radioactive"),
        EmojiSymbol("☣", "2623", "biohazard"),
        EmojiSymbol("⬆", "2b06", "up arrow"),
        EmojiSymbol("↗", "2197", "up-right arrow"),
        EmojiSymbol("➡", "27a1", "right arrow"),
        EmojiSymbol("↘", "2198", "down-right arrow"),
        EmojiSymbol("⬇", "2b07", "down arrow"),
        EmojiSymbol("↙", "2199", "down-left arrow"),
        EmojiSymbol("⬅", "2b05", "left arrow"),
        EmojiSymbol("↖", "2196", "up-left arrow"),
        EmojiSymbol("↕", "2195", "up-down arrow"),
        EmojiSymbol("↔", "2194", "left-right arrow"),
        EmojiSymbol("↩", "21a9", "right arrow curving left"),
        EmojiSymbol("↪", "21aa", "left arrow curving right"),
        EmojiSymbol("⤴", "2934", "right arrow curving up"),
        EmojiSymbol("⤵", "2935", "right arrow curving down"),
        EmojiSymbol("🔃", "1f503", "clockwise vertical arrows"),
        EmojiSymbol("🔄", "1f504", "counterclockwise arrows button"),
        EmojiSymbol("🔙", "1f519", "BACK arrow"),
        EmojiSymbol("🔚", "1f51a", "END arrow"),
        EmojiSymbol("🔛", "1f51b", "ON! arrow"),
        EmojiSymbol("🔜", "1f51c", "SOON arrow"),
        EmojiSymbol("🔝", "1f51d", "TOP arrow"),
        EmojiSymbol("🛐", "1f6d0", "place of worship"),
        EmojiSymbol("⚛", "269b", "atom symbol"),
        EmojiSymbol("🕉", "1f549", "om"),
        EmojiSymbol("✡", "2721", "star of David"),
        EmojiSymbol("☸", "2638", "wheel of dharma"),
        EmojiSymbol("☯", "262f", "yin yang"),
        EmojiSymbol("✝", "271d", "latin cross"),
        EmojiSymbol("☦", "2626", "orthodox cross"),
        EmojiSymbol("☪", "262a", "star and crescent"),
        EmojiSymbol("☮", "262e", "peace symbol"),
        EmojiSymbol("🕎", "1f54e", "menorah"),
        EmojiSymbol("🔯", "1f52f", "dotted six-pointed star"),
        EmojiSymbol("♈", "2648", "Aries"),
        EmojiSymbol("♉", "2649", "Taurus"),
        EmojiSymbol("♊", "264a", "Gemini"),
        EmojiSymbol("♋", "264b", "Cancer"),
        EmojiSymbol("♌", "264c", "Leo"),
        EmojiSymbol("♍", "264d", "Virgo"),
        EmojiSymbol("♎", "264e", "Libra"),
        EmojiSymbol("♏", "264f", "Scorpius"),
        EmojiSymbol("♐", "2650", "Sagittarius"),
        EmojiSymbol("♑", "2651", "Capricorn"),
        EmojiSymbol("♒", "2652", "Aquarius"),
        EmojiSymbol("♓", "2653", "Pisces"),
        EmojiSymbol("⛎", "26ce", "Ophiuchus"),
        EmojiSymbol("🔀", "1f500", "shuffle tracks button"),
        EmojiSymbol("🔁", "1f501", "repeat button"),
        EmojiSymbol("🔂", "1f502", "repeat single button"),
        EmojiSymbol("▶", "25b6", "play button"),
        EmojiSymbol("⏩", "23e9", "fast-forward button"),
        EmojiSymbol("⏭", "23ed", "next track button"),
        EmojiSymbol("⏯", "23ef", "play or pause button"),
        EmojiSymbol("◀", "25c0", "reverse button"),
        EmojiSymbol("⏪", "23ea", "fast reverse button"),
        EmojiSymbol("⏮", "23ee", "last track button"),
        EmojiSymbol("🔼", "1f53c", "up button"),
        EmojiSymbol("⏫", "23eb", "fast up button"),
        EmojiSymbol("🔽", "1f53d", "down button"),
        EmojiSymbol("⏬", "23ec", "fast down button"),
        EmojiSymbol("⏸", "23f8", "pause button"),
        EmojiSymbol("⏹", "23f9", "stop button"),
        EmojiSymbol("⏺", "23fa", "record button"),
        EmojiSymbol("⏏", "23cf", "eject button"),
        EmojiSymbol("🎦", "1f3a6", "cinema"),
        EmojiSymbol("🔅", "1f505", "dim button"),
        EmojiSymbol("🔆", "1f506", "bright button"),
        EmojiSymbol("📶", "1f4f6", "antenna bars"),
        EmojiSymbol("📳", "1f4f3", "vibration mode"),
        EmojiSymbol("📴", "1f4f4", "mobile phone off"),
        EmojiSymbol("♀", "2640", "female sign"),
        EmojiSymbol("♂", "2642", "male sign"),
        EmojiSymbol("⚕", "2695", "medical symbol"),
        EmojiSymbol("♻", "267b", "recycling symbol"),
        EmojiSymbol("⚜", "269c", "fleur-de-lis"),
        EmojiSymbol("🔱", "1f531", "trident emblem"),
        EmojiSymbol("📛", "1f4db", "name badge"),
        EmojiSymbol("🔰", "1f530", "Japanese symbol for beginner"),
        EmojiSymbol("⭕", "2b55", "heavy large circle"),
        EmojiSymbol("✅", "2705", "white heavy check mark"),
        EmojiSymbol("☑", "2611", "ballot box with check"),
        EmojiSymbol("✔", "2714", "heavy check mark"),
        EmojiSymbol("✖", "2716", "heavy multiplication x"),
        EmojiSymbol("❌", "274c", "cross mark"),
        EmojiSymbol("❎", "274e", "cross mark button"),
        EmojiSymbol("➕", "2795", "heavy plus sign"),
        EmojiSymbol("➖", "2796", "heavy minus sign"),
        EmojiSymbol("➗", "2797", "heavy division sign"),
        EmojiSymbol("➰", "27b0", "curly loop"),
        EmojiSymbol("➿", "27bf", "double curly loop"),
        EmojiSymbol("〽", "303d", "part alternation mark"),
        EmojiSymbol("✳", "2733", "eight-spoked asterisk"),
        EmojiSymbol("✴", "2734", "eight-pointed star"),
        EmojiSymbol("❇", "2747", "sparkle"),
        EmojiSymbol("‼", "203c", "double exclamation mark"),
        EmojiSymbol("⁉", "2049", "exclamation question mark"),
        EmojiSymbol("❓", "2753", "question mark"),
        EmojiSymbol("❔", "2754", "white question mark"),
        EmojiSymbol("❕", "2755", "white exclamation mark"),
        EmojiSymbol("❗", "2757", "exclamation mark"),
        EmojiSymbol("〰", "3030", "wavy dash"),
        EmojiSymbol("©", "00a9", "copyright"),
        EmojiSymbol("®", "00ae", "registered"),
        EmojiSymbol("™", "2122", "trade mark"),
        EmojiSymbol("#️⃣", "0023-fe0f-20e3", "keycap: #"),
        EmojiSymbol("*️⃣", "002a-fe0f-20e3", "keycap: *"),
        EmojiSymbol("0️⃣", "0030-fe0f-20e3", "keycap: 0"),
        EmojiSymbol("1️⃣", "0031-fe0f-20e3", "keycap: 1"),
        EmojiSymbol("2️⃣", "0032-fe0f-20e3", "keycap: 2"),
        EmojiSymbol("3️⃣", "0033-fe0f-20e3", "keycap: 3"),
        EmojiSymbol("4️⃣", "0034-fe0f-20e3", "keycap: 4"),
        EmojiSymbol("5️⃣", "0035-fe0f-20e3", "keycap: 5"),
        EmojiSymbol("6️⃣", "0036-fe0f-20e3", "keycap: 6"),
        EmojiSymbol("7️⃣", "0037-fe0f-20e3", "keycap: 7"),
        EmojiSymbol("8️⃣", "0038-fe0f-20e3", "keycap: 8"),
        EmojiSymbol("9️⃣", "0039-fe0f-20e3", "keycap: 9"),
        EmojiSymbol("🔟", "1f51f", "keycap 10"),
        EmojiSymbol("💯", "1f4af", "hundred points"),
        EmojiSymbol("🔠", "1f520", "input latin uppercase"),
        EmojiSymbol("🔡", "1f521", "input latin lowercase"),
        EmojiSymbol("🔢", "1f522", "input numbers"),
        EmojiSymbol("🔣", "1f523", "input symbols"),
        EmojiSymbol("🔤", "1f524", "input latin letters"),
        EmojiSymbol("🅰", "1f170", "A button (blood type)"),
        EmojiSymbol("🆎", "1f18e", "AB button (blood type)"),
        EmojiSymbol("🅱", "1f171", "B button (blood type)"),
        EmojiSymbol("🆑", "1f191", "CL button"),
        EmojiSymbol("🆒", "1f192", "COOL button"),
        EmojiSymbol("🆓", "1f193", "FREE button"),
        EmojiSymbol("ℹ", "2139", "information"),
        EmojiSymbol("🆔", "1f194", "ID button"),
        EmojiSymbol("Ⓜ", "24c2", "circled M"),
        EmojiSymbol("🆕", "1f195", "NEW button"),
        EmojiSymbol("🆖", "1f196", "NG button"),
        EmojiSymbol("🅾", "1f17e", "O button (blood type)"),
        EmojiSymbol("🆗", "1f197", "OK button"),
        EmojiSymbol("🅿", "1f17f", "P button"),
        EmojiSymbol("🆘", "1f198", "SOS button"),
        EmojiSymbol("🆙", "1f199", "UP! button"),
        EmojiSymbol("🆚", "1f19a", "VS button"),
        EmojiSymbol("🈁", "1f201", "Japanese “here” button"),
        EmojiSymbol("🈂", "1f202", "Japanese “service charge” button"),
        EmojiSymbol("🈷", "1f237", "Japanese “monthly amount” button"),
        EmojiSymbol("🈶", "1f236", "Japanese “not free of charge” button"),
        EmojiSymbol("🈯", "1f22f", "Japanese “reserved” button"),
        EmojiSymbol("🉐", "1f250", "Japanese “bargain” button"),
        EmojiSymbol("🈹", "1f239", "Japanese “discount” button"),
        EmojiSymbol("🈚", "1f21a", "Japanese “free of charge” button"),
        EmojiSymbol("🈲", "1f232", "Japanese “prohibited” button"),
        EmojiSymbol("🉑", "1f251", "Japanese “acceptable” button"),
        EmojiSymbol("🈸", "1f238", "Japanese “application” button"),
        EmojiSymbol("🈴", "1f234", "Japanese “passing grade” button"),
        EmojiSymbol("🈳", "1f233", "Japanese “vacancy” button"),
        EmojiSymbol("㊗", "3297", "Japanese “congratulations” button"),
        EmojiSymbol("㊙", "3299", "Japanese “secret” button"),
        EmojiSymbol("🈺", "1f23a", "Japanese “open for business” button"),
        EmojiSymbol("🈵", "1f235", "Japanese “no vacancy” button"),
        EmojiSymbol("▪", "25aa", "black small square"),
        EmojiSymbol("▫", "25ab", "white small square"),
        EmojiSymbol("◻", "25fb", "white medium square"),
        EmojiSymbol("◼", "25fc", "black medium square"),
        EmojiSymbol("◽", "25fd", "white medium-small square"),
        EmojiSymbol("◾", "25fe", "black medium-small square"),
        EmojiSymbol("⬛", "2b1b", "black large square"),
        EmojiSymbol("⬜", "2b1c", "white large square"),
        EmojiSymbol("🔶", "1f536", "large orange diamond"),
        EmojiSymbol("🔷", "1f537", "large blue diamond"),
        EmojiSymbol("🔸", "1f538", "small orange diamond"),
        EmojiSymbol("🔹", "1f539", "small blue diamond"),
        EmojiSymbol("🔺", "1f53a", "red triangle pointed up"),
        EmojiSymbol("🔻", "1f53b", "red triangle pointed down"),
        EmojiSymbol("💠", "1f4a0", "diamond with a dot"),
        EmojiSymbol("🔘", "1f518", "radio button"),
        EmojiSymbol("🔲", "1f532", "black square button"),
        EmojiSymbol("🔳", "1f533", "white square button"),
        EmojiSymbol("⚪", "26aa", "white circle"),
        EmojiSymbol("⚫", "26ab", "black circle"),
        EmojiSymbol("🔴", "1f534", "red circle"),
        EmojiSymbol("🔵", "1f535", "blue circle")
)
