package koma.gui.element.emoji.category;

val Travel = listOf(
        EmojiSymbol("🌍", "1f30d", "globe showing Europe-Africa"),
        EmojiSymbol("🌎", "1f30e", "globe showing Americas"),
        EmojiSymbol("🌏", "1f30f", "globe showing Asia-Australia"),
        EmojiSymbol("🌐", "1f310", "globe with meridians"),
        EmojiSymbol("🗺", "1f5fa", "world map"),
        EmojiSymbol("🗾", "1f5fe", "map of Japan"),
        EmojiSymbol("🏔", "1f3d4", "snow-capped mountain"),
        EmojiSymbol("⛰", "26f0", "mountain"),
        EmojiSymbol("🌋", "1f30b", "volcano"),
        EmojiSymbol("🗻", "1f5fb", "mount fuji"),
        EmojiSymbol("🏕", "1f3d5", "camping"),
        EmojiSymbol("🏖", "1f3d6", "beach with umbrella"),
        EmojiSymbol("🏜", "1f3dc", "desert"),
        EmojiSymbol("🏝", "1f3dd", "desert island"),
        EmojiSymbol("🏞", "1f3de", "national park"),
        EmojiSymbol("🏟", "1f3df", "stadium"),
        EmojiSymbol("🏛", "1f3db", "classical building"),
        EmojiSymbol("🏗", "1f3d7", "building construction"),
        EmojiSymbol("🏘", "1f3d8", "houses"),
        EmojiSymbol("🏙", "1f3d9", "cityscape"),
        EmojiSymbol("🏚", "1f3da", "derelict house"),
        EmojiSymbol("🏠", "1f3e0", "house"),
        EmojiSymbol("🏡", "1f3e1", "house with garden"),
        EmojiSymbol("🏢", "1f3e2", "office building"),
        EmojiSymbol("🏣", "1f3e3", "Japanese post office"),
        EmojiSymbol("🏤", "1f3e4", "post office"),
        EmojiSymbol("🏥", "1f3e5", "hospital"),
        EmojiSymbol("🏦", "1f3e6", "bank"),
        EmojiSymbol("🏨", "1f3e8", "hotel"),
        EmojiSymbol("🏩", "1f3e9", "love hotel"),
        EmojiSymbol("🏪", "1f3ea", "convenience store"),
        EmojiSymbol("🏫", "1f3eb", "school"),
        EmojiSymbol("🏬", "1f3ec", "department store"),
        EmojiSymbol("🏭", "1f3ed", "factory"),
        EmojiSymbol("🏯", "1f3ef", "Japanese castle"),
        EmojiSymbol("🏰", "1f3f0", "castle"),
        EmojiSymbol("💒", "1f492", "wedding"),
        EmojiSymbol("🗼", "1f5fc", "Tokyo tower"),
        EmojiSymbol("🗽", "1f5fd", "Statue of Liberty"),
        EmojiSymbol("⛪", "26ea", "church"),
        EmojiSymbol("🕌", "1f54c", "mosque"),
        EmojiSymbol("🕍", "1f54d", "synagogue"),
        EmojiSymbol("⛩", "26e9", "shinto shrine"),
        EmojiSymbol("🕋", "1f54b", "kaaba"),
        EmojiSymbol("⛲", "26f2", "fountain"),
        EmojiSymbol("⛺", "26fa", "tent"),
        EmojiSymbol("🌁", "1f301", "foggy"),
        EmojiSymbol("🌃", "1f303", "night with stars"),
        EmojiSymbol("🌄", "1f304", "sunrise over mountains"),
        EmojiSymbol("🌅", "1f305", "sunrise"),
        EmojiSymbol("🌆", "1f306", "cityscape at dusk"),
        EmojiSymbol("🌇", "1f307", "sunset"),
        EmojiSymbol("🌉", "1f309", "bridge at night"),
        EmojiSymbol("♨", "2668", "hot springs"),
        EmojiSymbol("🌌", "1f30c", "milky way"),
        EmojiSymbol("🎠", "1f3a0", "carousel horse"),
        EmojiSymbol("🎡", "1f3a1", "ferris wheel"),
        EmojiSymbol("🎢", "1f3a2", "roller coaster"),
        EmojiSymbol("💈", "1f488", "barber pole"),
        EmojiSymbol("🎪", "1f3aa", "circus tent"),
        EmojiSymbol("🎭", "1f3ad", "performing arts"),
        EmojiSymbol("🖼", "1f5bc", "framed picture"),
        EmojiSymbol("🎨", "1f3a8", "artist palette"),
        EmojiSymbol("🎰", "1f3b0", "slot machine"),
        EmojiSymbol("🚂", "1f682", "locomotive"),
        EmojiSymbol("🚃", "1f683", "railway car"),
        EmojiSymbol("🚄", "1f684", "high-speed train"),
        EmojiSymbol("🚅", "1f685", "bullet train"),
        EmojiSymbol("🚆", "1f686", "train"),
        EmojiSymbol("🚇", "1f687", "metro"),
        EmojiSymbol("🚈", "1f688", "light rail"),
        EmojiSymbol("🚉", "1f689", "station"),
        EmojiSymbol("🚊", "1f68a", "tram"),
        EmojiSymbol("🚝", "1f69d", "monorail"),
        EmojiSymbol("🚞", "1f69e", "mountain railway"),
        EmojiSymbol("🚋", "1f68b", "tram car"),
        EmojiSymbol("🚌", "1f68c", "bus"),
        EmojiSymbol("🚍", "1f68d", "oncoming bus"),
        EmojiSymbol("🚎", "1f68e", "trolleybus"),
        EmojiSymbol("🚐", "1f690", "minibus"),
        EmojiSymbol("🚑", "1f691", "ambulance"),
        EmojiSymbol("🚒", "1f692", "fire engine"),
        EmojiSymbol("🚓", "1f693", "police car"),
        EmojiSymbol("🚔", "1f694", "oncoming police car"),
        EmojiSymbol("🚕", "1f695", "taxi"),
        EmojiSymbol("🚖", "1f696", "oncoming taxi"),
        EmojiSymbol("🚗", "1f697", "automobile"),
        EmojiSymbol("🚘", "1f698", "oncoming automobile"),
        EmojiSymbol("🚙", "1f699", "sport utility vehicle"),
        EmojiSymbol("🚚", "1f69a", "delivery truck"),
        EmojiSymbol("🚛", "1f69b", "articulated lorry"),
        EmojiSymbol("🚜", "1f69c", "tractor"),
        EmojiSymbol("🚲", "1f6b2", "bicycle"),
        EmojiSymbol("🛴", "1f6f4", "kick scooter"),
        EmojiSymbol("🛵", "1f6f5", "motor scooter"),
        EmojiSymbol("🚏", "1f68f", "bus stop"),
        EmojiSymbol("🛣", "1f6e3", "motorway"),
        EmojiSymbol("🛤", "1f6e4", "railway track"),
        EmojiSymbol("⛽", "26fd", "fuel pump"),
        EmojiSymbol("🚨", "1f6a8", "police car light"),
        EmojiSymbol("🚥", "1f6a5", "horizontal traffic light"),
        EmojiSymbol("🚦", "1f6a6", "vertical traffic light"),
        EmojiSymbol("🚧", "1f6a7", "construction"),
        EmojiSymbol("🛑", "1f6d1", "stop sign"),
        EmojiSymbol("⚓", "2693", "anchor"),
        EmojiSymbol("⛵", "26f5", "sailboat"),
        EmojiSymbol("🛶", "1f6f6", "canoe"),
        EmojiSymbol("🚤", "1f6a4", "speedboat"),
        EmojiSymbol("🛳", "1f6f3", "passenger ship"),
        EmojiSymbol("⛴", "26f4", "ferry"),
        EmojiSymbol("🛥", "1f6e5", "motor boat"),
        EmojiSymbol("🚢", "1f6a2", "ship"),
        EmojiSymbol("✈", "2708", "airplane"),
        EmojiSymbol("🛩", "1f6e9", "small airplane"),
        EmojiSymbol("🛫", "1f6eb", "airplane departure"),
        EmojiSymbol("🛬", "1f6ec", "airplane arrival"),
        EmojiSymbol("💺", "1f4ba", "seat"),
        EmojiSymbol("🚁", "1f681", "helicopter"),
        EmojiSymbol("🚟", "1f69f", "suspension railway"),
        EmojiSymbol("🚠", "1f6a0", "mountain cableway"),
        EmojiSymbol("🚡", "1f6a1", "aerial tramway"),
        EmojiSymbol("🛰", "1f6f0", "satellite"),
        EmojiSymbol("🚀", "1f680", "rocket"),
        EmojiSymbol("🛸", "1f6f8", "flying saucer"),
        EmojiSymbol("🛎", "1f6ce", "bellhop bell"),
        EmojiSymbol("🚪", "1f6aa", "door"),
        EmojiSymbol("🛏", "1f6cf", "bed"),
        EmojiSymbol("🛋", "1f6cb", "couch and lamp"),
        EmojiSymbol("🚽", "1f6bd", "toilet"),
        EmojiSymbol("🚿", "1f6bf", "shower"),
        EmojiSymbol("🛁", "1f6c1", "bathtub"),
        EmojiSymbol("⌛", "231b", "hourglass done"),
        EmojiSymbol("⏳", "23f3", "hourglass not done"),
        EmojiSymbol("⌚", "231a", "watch"),
        EmojiSymbol("⏰", "23f0", "alarm clock"),
        EmojiSymbol("⏱", "23f1", "stopwatch"),
        EmojiSymbol("⏲", "23f2", "timer clock"),
        EmojiSymbol("🕰", "1f570", "mantelpiece clock"),
        EmojiSymbol("🕛", "1f55b", "twelve o’clock"),
        EmojiSymbol("🕧", "1f567", "twelve-thirty"),
        EmojiSymbol("🕐", "1f550", "one o’clock"),
        EmojiSymbol("🕜", "1f55c", "one-thirty"),
        EmojiSymbol("🕑", "1f551", "two o’clock"),
        EmojiSymbol("🕝", "1f55d", "two-thirty"),
        EmojiSymbol("🕒", "1f552", "three o’clock"),
        EmojiSymbol("🕞", "1f55e", "three-thirty"),
        EmojiSymbol("🕓", "1f553", "four o’clock"),
        EmojiSymbol("🕟", "1f55f", "four-thirty"),
        EmojiSymbol("🕔", "1f554", "five o’clock"),
        EmojiSymbol("🕠", "1f560", "five-thirty"),
        EmojiSymbol("🕕", "1f555", "six o’clock"),
        EmojiSymbol("🕡", "1f561", "six-thirty"),
        EmojiSymbol("🕖", "1f556", "seven o’clock"),
        EmojiSymbol("🕢", "1f562", "seven-thirty"),
        EmojiSymbol("🕗", "1f557", "eight o’clock"),
        EmojiSymbol("🕣", "1f563", "eight-thirty"),
        EmojiSymbol("🕘", "1f558", "nine o’clock"),
        EmojiSymbol("🕤", "1f564", "nine-thirty"),
        EmojiSymbol("🕙", "1f559", "ten o’clock"),
        EmojiSymbol("🕥", "1f565", "ten-thirty"),
        EmojiSymbol("🕚", "1f55a", "eleven o’clock"),
        EmojiSymbol("🕦", "1f566", "eleven-thirty"),
        EmojiSymbol("🌑", "1f311", "new moon"),
        EmojiSymbol("🌒", "1f312", "waxing crescent moon"),
        EmojiSymbol("🌓", "1f313", "first quarter moon"),
        EmojiSymbol("🌔", "1f314", "waxing gibbous moon"),
        EmojiSymbol("🌕", "1f315", "full moon"),
        EmojiSymbol("🌖", "1f316", "waning gibbous moon"),
        EmojiSymbol("🌗", "1f317", "last quarter moon"),
        EmojiSymbol("🌘", "1f318", "waning crescent moon"),
        EmojiSymbol("🌙", "1f319", "crescent moon"),
        EmojiSymbol("🌚", "1f31a", "new moon face"),
        EmojiSymbol("🌛", "1f31b", "first quarter moon face"),
        EmojiSymbol("🌜", "1f31c", "last quarter moon face"),
        EmojiSymbol("🌡", "1f321", "thermometer"),
        EmojiSymbol("☀", "2600", "sun"),
        EmojiSymbol("🌝", "1f31d", "full moon face"),
        EmojiSymbol("🌞", "1f31e", "sun with face"),
        EmojiSymbol("⭐", "2b50", "white medium star"),
        EmojiSymbol("🌟", "1f31f", "glowing star"),
        EmojiSymbol("🌠", "1f320", "shooting star"),
        EmojiSymbol("☁", "2601", "cloud"),
        EmojiSymbol("⛅", "26c5", "sun behind cloud"),
        EmojiSymbol("⛈", "26c8", "cloud with lightning and rain"),
        EmojiSymbol("🌤", "1f324", "sun behind small cloud"),
        EmojiSymbol("🌥", "1f325", "sun behind large cloud"),
        EmojiSymbol("🌦", "1f326", "sun behind rain cloud"),
        EmojiSymbol("🌧", "1f327", "cloud with rain"),
        EmojiSymbol("🌨", "1f328", "cloud with snow"),
        EmojiSymbol("🌩", "1f329", "cloud with lightning"),
        EmojiSymbol("🌪", "1f32a", "tornado"),
        EmojiSymbol("🌫", "1f32b", "fog"),
        EmojiSymbol("🌬", "1f32c", "wind face"),
        EmojiSymbol("🌀", "1f300", "cyclone"),
        EmojiSymbol("🌈", "1f308", "rainbow"),
        EmojiSymbol("🌂", "1f302", "closed umbrella"),
        EmojiSymbol("☂", "2602", "umbrella"),
        EmojiSymbol("☔", "2614", "umbrella with rain drops"),
        EmojiSymbol("⛱", "26f1", "umbrella on ground"),
        EmojiSymbol("⚡", "26a1", "high voltage"),
        EmojiSymbol("❄", "2744", "snowflake"),
        EmojiSymbol("☃", "2603", "snowman"),
        EmojiSymbol("⛄", "26c4", "snowman without snow"),
        EmojiSymbol("☄", "2604", "comet"),
        EmojiSymbol("🔥", "1f525", "fire"),
        EmojiSymbol("💧", "1f4a7", "droplet"),
        EmojiSymbol("🌊", "1f30a", "water wave")
)
